In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
dizi=np.array([1,2,3,4])
print(dizi)

[1 2 3 4]


In [ ]:
import numpy as np

In [5]:
array = np.array([1, 2, 3, 4, 5], dtype=int)
print("Array:", array)

Array: [1 2 3 4 5]


In [6]:
print("Arrayin Boyutu:", array.shape)

Arrayin Boyutu: (5,)


In [7]:
print("Arraydeki Eleman Sayısı:", array.size)

Arraydeki Eleman Sayısı: 5


In [8]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Array:\n", array_3d)

3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [9]:
array1=np.array(36)
array2=np.array([1,2,3,4])
array3=np.array([[1,2,3],[4,5,6],[7,8,9]])


print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

0
1
2


In [10]:
array_1d = np.array([10, 20, 30, 40, 50])
print("1D Array:", array_1d)

1D Array: [10 20 30 40 50]


In [11]:
print("1D Array [2]:", array_1d[2])

1D Array [2]: 30


In [12]:
print("1D Array [1:4]:", array_1d[1:4]) 

1D Array [1:4]: [20 30 40]


In [13]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", array_2d)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print("2D Array 2. Satır:", array_2d[1, :]) 

2D Array 2. Satır: [4 5 6]


In [15]:
print("2D Array 2. Sütun:", array_2d[:, 1])

2D Array 2. Sütun: [2 5 8]


In [16]:
print("2D Array Alt Matris:\n", array_2d[0:2, 1:3]) 

2D Array Alt Matris:
 [[2 3]
 [5 6]]


In [17]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Array:\n", array_3d)

3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
print("3D Array [1, 1, 2]:", array_3d[1, 1, 2])

3D Array [1, 1, 2]: 12


In [19]:
print("3D Array 1. Katman:\n", array_3d[0, :, :])

3D Array 1. Katman:
 [[1 2 3]
 [4 5 6]]


In [20]:
print("3D Array 1. Katman 2. Satır:", array_3d[0, 1, :]) 

3D Array 1. Katman 2. Satır: [4 5 6]


In [21]:
print("3D Array 2. Katman 2. Sütun:", array_3d[:, 1, 1])

3D Array 2. Katman 2. Sütun: [ 5 11]


In [22]:
print("3D Array Alt Matris:\n", array_3d[0:2, 0:2, 1:3]) 

3D Array Alt Matris:
 [[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]


In [31]:

# 2x3 boyutlarında sıfırlardan oluşan bir array
sıfırlar_array = np.zeros((2, 3))
print("Sıfırlardan Oluşan Array:\n", sıfırlar_array)

# 2x3 boyutlarında birlerden oluşan bir array
olanlar_array = np.ones((2, 3))
print("Birlerden Oluşan Array:\n", olanlar_array)

# Satır bazında birleştirme
dikey_stack = np.vstack((sıfırlar_array, olanlar_array))
print("Satır Bazında Birleştirilmiş Array:\n", dikey_stack)

# Sütun bazında birleştirme
yatay_stack = np.hstack((sıfırlar_array, olanlar_array))
print("Sütun Bazında Birleştirilmiş Array:\n", yatay_stack)

Sıfırlardan Oluşan Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Birlerden Oluşan Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Satır Bazında Birleştirilmiş Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
Sütun Bazında Birleştirilmiş Array:
 [[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
